### ISSUE TITLE
File 

### ISSUE THREAD

**Issue by chenqkaa** [nickastrin/VANETs-Project#1]
Respected author, thank you for sharing the documents. However, we have noticed that some files are missing. vehicle.csv. Please supplement the missing files as soon as possible so that we can read and understand your work completely. Thank you for your cooperation.

**Comment by nickastrin** [comment]
Hello,
The vehicle.csv is a file automatically produced by the CarHandler script. When the simulation begins, the car node [0] writes the file by sending a message with CurrentState::WRITING, and every 75 seconds the file is updated with the new positions of the vehicles in the simulation. The person running the simulation must make sure that the node assigned to write the file is currently persent in the simulation. This procedure can be seen in the CarHandler.cc file in the functions initializingMsg() and writingMsg().

**Comment by chenqkaa** [comment]
So much thanks.Thank you for your reply. 😘 If you don't glance me, so much time will be wasted.I think I will need your help in the future study. Could you give me your email? 发自我的荣耀手机-------- 原始邮件 --------发件人： Nikos Astrinakis ***@***.***>日期： 2023年11月16日周四 傍晚6:17收件人： nickastrin/VANETs-Master-Thesis ***@***.***>抄送： chenqkaa ***@***.***>, Author ***@***.***>主    题： Re: [nickastrin/VANETs-Master-Thesis] File  (Issue #1)
Hello,
The vehicle.csv is a file automatically produced by the CarHandler script. When the simulation begins, the car node [0] writes the file by sending a message with CurrentState::WRITING, and every 75 seconds the file is updated with the new positions of the vehicles in the simulation. The person running the simulation must make sure that the node assigned to write the file is currently persent in the simulation. This procedure can be seen in the CarHandler.cc file in the functions initializingMsg() and writingMsg().
